[book]
authors = ["clearloop"]
language = "en"
multilingual = false
src = "src"
title = "master-leetcode"

[build]
build-dir = "docs"

[output.html]
default-theme = "dark"
preferred-dark-theme = "ayu"