[sys]
categories = [
    'algorithms',
    'database',
    'shell',
]
langs = [
    'bash',
    'c',
    'cpp',
    'csharp',
    'golang',
    'java',
    'javascript',
    'kotlin',
    'mysql',
    'php',
    'python',
    'python3',
    'ruby',
    'rust',
    'scala',
    'swift',
]

[sys.urls]
test = 'https://leetcode.com/problems/$slug/interpret_solution/'
problem = 'https://leetcode.com/problems/$slug/description/'
submissions = 'https://leetcode.com/api/submissions/$slug'
verify = 'https://leetcode.com/submissions/detail/$id/check/'
problems = 'https://leetcode.com/api/problems/$category/'
login = 'https://leetcode.com/accounts/login/'
submit = 'https://leetcode.com/problems/$slug/submit/'
base = 'https://leetcode.com'
tag = 'https://leetcode.com/tag/$slug/'
graphql = 'https://leetcode.com/graphql'
favorites = 'https://leetcode.com/list/api/questions'
session = 'https://leetcode.com/session/'
submission = 'https://leetcode.com/submissions/detail/$id/'
favorite_delete = 'https://leetcode.com/list/api/questions/$hash/$id'

[code]
editor = 'emacs'
lang = 'rust'
pick = '${fid}.${slug}'
submission = '${fid}.${slug}.${sid}.${ac}'

[cookies]
csrf = 'FWtgVTWhH5v3aseN7MGjSdGpnfwMb8dRDPMhQwDwZX9GGZeIFKYCRpXahlYQYS99'
session = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfYXV0aF91c2VyX2lkIjoiMTExNTcyMSIsIl9hdXRoX3VzZXJfYmFja2VuZCI6ImFsbGF1dGguYWNjb3VudC5hdXRoX2JhY2tlbmRzLkF1dGhlbnRpY2F0aW9uQmFja2VuZCIsIl9hdXRoX3VzZXJfaGFzaCI6ImFjZDRjOGZiMjYzYzY1OTkzMWU3NGFkODJhZWUzM2I4NTA3ZWZjODciLCJpZCI6MTExNTcyMSwiZW1haWwiOiJ1ZHRyb2tpYUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6InVkdHJva2lhIiwidXNlcl9zbHVnIjoidWR0cm9raWEiLCJhdmF0YXIiOiJodHRwczovL2Fzc2V0cy5sZWV0Y29kZS5jb20vdXNlcnMvdWR0cm9raWEvYXZhdGFyXzE1MTkxOTE2NTEucG5nIiwidGltZXN0YW1wIjoiMjAyMC0wMS0wNSAyMTo0ODozMC4xODAxMjMrMDA6MDAiLCJJUCI6IjEyOS4yMjYuMTIyLjE2NCIsIklERU5USVRZIjoiOWQ3MmYzMDc1NTU1ODU4MjkxOGMxZTZiNTAwODk5MDcifQ.wKGN6SBBhC-Jh9XBpx2cdCGq6SJvAJMznN60dU4zppY'

[storage]
cache = 'Problems'
code = 'code'
root = '~/.leetcode'
